clang-tidy: drop unused io
Clang under -Werror flagged boost::asio::io_context 'io' as an unused
private field in UBootEnvMgr. The class does not perform async work;
it uses boost::process to call fw_printenv/fw_setenv synchronously.

Fixed below error
'''
../include/u-boot-env-mgr.hpp:31:30: error: private field 'io' is not used [-Werror,-Wunused-private-field]
   31 |     boost::asio::io_context& io;
'''

Change-Id: I7eb2a23a0766c8a670e9ef79d1dbf468d1f0ec59
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>
Signed-off-by: Akash Arunkumar <mirrorghost007@gmail.com>